/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busquedaincersionhash;

import java.awt.Graphics;
import javax.swing.JOptionPane;

/**
 *
 * @author elias
 */
public class TransformacionDeClaves extends javax.swing.JFrame {

    Graphics graphics;
    
    Casilla casillas[];
    
    /**
     * Creates new form TransformacionDeClaves
     */
    public TransformacionDeClaves() {
        initComponents();
        casillas = new Casilla[10];
        for(int i = 0; i<casillas.length;i++){
            casillas[i] = new Casilla(  (this.getWidth()/10)*(i) + 10  ,200,0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        solu_coli = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        insercion_busqueda = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        metodo_busqueda = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metodos De Transformacion De Claves");
        setResizable(false);

        jButton1.setText("Insertar Elemento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar Elemento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar Elemento");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Solucionar Colisiones por:");

        solu_coli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prueba Lineal", "Prueba Cuadratica", "Doble Direccion Hash" }));

        jLabel2.setText("Buscar/Insertar por:");

        insercion_busqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modulo", "Cuadrado", "Plegamiento", "Truncamiento" }));
        insercion_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insercion_busquedaActionPerformed(evt);
            }
        });

        jLabel3.setText("Metodo de busqueda");

        metodo_busqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mismo Metodo Hash", "Secuencial", "Binaria" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(solu_coli, 0, 158, Short.MAX_VALUE)
                    .addComponent(insercion_busqueda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(metodo_busqueda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(insercion_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(solu_coli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(metodo_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int value = Integer.parseInt(JOptionPane.showInputDialog(this,"Cual sera el valor a introducir (este tambien se usara como clave)"));       
        Casilla c = null;
        switch(insercion_busqueda.getSelectedIndex()){
            //modulo
            case 0:
                Hash.insertarElemento(value, -1, casillas, Hash.METODO_MOD, solu_coli.getSelectedIndex());
                break;
            //cuadrado
            case 1:
                Hash.insertarElemento(value, -1, casillas, Hash.METODO_CUADRADO, solu_coli.getSelectedIndex());
                break;
            //plegamiento
            case 2:
                 Hash.insertarElemento(value, -1, casillas, Hash.METODO_PLEGAMIENTO, solu_coli.getSelectedIndex());
                break;
            //truncamiento
            case 3:
                Hash.insertarElemento(value, -1, casillas, Hash.METODO_TRUNCAMIENTO, solu_coli.getSelectedIndex());
                break;
            //modulo
            default:
                Hash.insertarElemento(value, -1, casillas, Hash.METODO_MOD, solu_coli.getSelectedIndex());
                break;
        }
        
        //repintamos
        repaint();        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int b = Integer.parseInt(JOptionPane.showInputDialog(this,"Que valor desea buscar en el arreglo?"));
        switch(metodo_busqueda.getSelectedIndex()){
            case 0:
                Hash.busquedaSecuencial(b, casillas);
                break;
            case 1:
                Hash.buscarPorHash(b, casillas,insercion_busqueda.getSelectedIndex());
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Este metodo requiere que el arreglo este ordenado");
                break;
            default:
                Hash.busquedaSecuencial(b, casillas);
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int b = Integer.parseInt(JOptionPane.showInputDialog(this,"Que valor desea eliminar del arreglo?"));
        byte flag = 0;
        switch(metodo_busqueda.getSelectedIndex()){
            case 0:
                flag = Hash.busquedaSecuencial(b, casillas);
                break;
            case 1:
                flag = Hash.buscarPorHash(b, casillas,insercion_busqueda.getSelectedIndex());
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Este metodo requiere que el arreglo este ordenado");
                break;
            default:
                flag = Hash.busquedaSecuencial(b, casillas);
                break;
        }
        if(flag!=-1){
            casillas[flag].setData(0);
            JOptionPane.showMessageDialog(null, "Elemento eliminado");
            repaint();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void insercion_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insercion_busquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insercion_busquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransformacionDeClaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransformacionDeClaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransformacionDeClaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransformacionDeClaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransformacionDeClaves().setVisible(true);
            }
        });
    }
    
    @Override
     public void paint (Graphics g){
        super.paint(g);
        graphics = g;
        pintarCasillas();
    }
     
     public void pintarCasillas(){
        for (Casilla casilla : casillas) {
            casilla.paint(graphics);
        } 
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> insercion_busqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> metodo_busqueda;
    private javax.swing.JComboBox<String> solu_coli;
    // End of variables declaration//GEN-END:variables

}
